# Generated by Django 3.1.1 on 2020-09-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTuitionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='logo')),
                ('about', models.TextField()),
                ('about_image1', models.ImageField(upload_to='system')),
                ('about_image2', models.ImageField(upload_to='system')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=40)),
                ('facebook', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE'), ('other', 'OTHER')], max_length=10)),
                ('photo', models.ImageField(upload_to='teacher')),
                ('phone_no', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=40)),
                ('education', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=40)),
                ('cv', models.FileField(upload_to='cv')),
                ('citizenship', models.FileField(upload_to='citizenship')),
                ('subject', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
