# Generated by Django 3.1.1 on 2020-09-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeTuitionSystem',
        ),
    ]
