# Generated by Django 3.1.4 on 2021-04-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='experience',
        ),
    ]
