# Generated by Django 3.1.1 on 2020-09-21 13:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hometuitionsystem',
            name='contact',
        ),
        migrations.AddField(
            model_name='hometuitionsystem',
            name='about_image1',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometuitionsystem',
            name='about_image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='system'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometuitionsystem',
            name='facebook',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometuitionsystem',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hometuitionsystem',
            name='phone_no',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
