# Generated by Django 3.1.1 on 2020-09-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hometuitionapp', '0002_delete_hometuitionsystem'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTuitionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='logo')),
                ('about', models.TextField()),
                ('about_image1', models.ImageField(upload_to='system')),
                ('about_image2', models.ImageField(upload_to='system')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=40)),
                ('facebook', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
