# Generated by Django 3.1.1 on 2020-09-22 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0002_auto_20200921_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometuitionsystem',
            name='name',
            field=models.CharField(max_length=60),
        ),
    ]
