# Generated by Django 3.1.1 on 2020-09-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0003_auto_20200922_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hometuitionsystem',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
