# Generated by Django 3.1.4 on 2020-12-15 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hometuitionapp', '0006_auto_20201120_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['id']},
        ),
    ]
